name: Feature request
description: Suggest an idea for this project
title: 'feat: '
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Briefly describe the issue and the improvement you expect.
      placeholder: e.g. It is hard to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Outline the feature or solution you are suggesting.
      placeholder: e.g. Add a setting to...
    validations:
      required: true
